import { Seller, MonthlyGoal, DailyRecord, Mission, MissionProgress } from './types';

export const INITIAL_SELLERS: Seller[] = [
  { id: 'jose', name: 'José', storeId: '102', avatarColor: 'from-orange-500 to-red-600', carImage: 'formula' },
  { id: 'elmer', name: 'Elmer', storeId: '102', avatarColor: 'from-emerald-400 to-green-600', carImage: 'gt' },
  { id: 'daniel', name: 'Daniel', storeId: '218', avatarColor: 'from-blue-400 to-indigo-600', carImage: 'cyber' },
  { id: 'rossi', name: 'Rossi', storeId: '218', avatarColor: 'from-pink-400 to-purple-600', carImage: 'kart' },
];

export const INITIAL_GOALS: MonthlyGoal[] = [
  { sellerId: 'jose', month: '2026-07', goalAmount: 200000 },
  { sellerId: 'elmer', month: '2026-07', goalAmount: 100000 },
  { sellerId: 'daniel', month: '2026-07', goalAmount: 150000 },
  { sellerId: 'rossi', month: '2026-07', goalAmount: 100000 },
];

export const INITIAL_RECORDS: DailyRecord[] = [
  // --- José (Tienda 102) ---
  {
    id: 'rec-jose-1',
    date: '2026-07-01',
    sellerId: 'jose',
    storeId: '102',
    salesWithTax: 18000,
    salesWithoutTax: 15254,
    productsSold: 22,
    clientsServed: 12,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-jose-2',
    date: '2026-07-02',
    sellerId: 'jose',
    storeId: '102',
    salesWithTax: 22000,
    salesWithoutTax: 18644,
    productsSold: 28,
    clientsServed: 15,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-jose-3',
    date: '2026-07-03',
    sellerId: 'jose',
    storeId: '102',
    salesWithTax: 15000,
    salesWithoutTax: 12711,
    productsSold: 18,
    clientsServed: 10,
    cleanlinessPassed: false,
    punctualityPassed: true,
  },
  {
    id: 'rec-jose-4',
    date: '2026-07-04',
    sellerId: 'jose',
    storeId: '102',
    salesWithTax: 25000,
    salesWithoutTax: 21186,
    productsSold: 30,
    clientsServed: 16,
    cleanlinessPassed: true,
    punctualityPassed: false,
  },
  {
    id: 'rec-jose-5',
    date: '2026-07-05',
    sellerId: 'jose',
    storeId: '102',
    salesWithTax: 12000,
    salesWithoutTax: 10169,
    productsSold: 15,
    clientsServed: 8,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },

  // --- Elmer (Tienda 102) ---
  {
    id: 'rec-elmer-1',
    date: '2026-07-01',
    sellerId: 'elmer',
    storeId: '102',
    salesWithTax: 10000,
    salesWithoutTax: 8474,
    productsSold: 12,
    clientsServed: 8,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-elmer-2',
    date: '2026-07-02',
    sellerId: 'elmer',
    storeId: '102',
    salesWithTax: 8000,
    salesWithoutTax: 6779,
    productsSold: 10,
    clientsServed: 6,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-elmer-3',
    date: '2026-07-03',
    sellerId: 'elmer',
    storeId: '102',
    salesWithTax: 12000,
    salesWithoutTax: 10169,
    productsSold: 14,
    clientsServed: 9,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-elmer-4',
    date: '2026-07-04',
    sellerId: 'elmer',
    storeId: '102',
    salesWithTax: 9000,
    salesWithoutTax: 7627,
    productsSold: 11,
    clientsServed: 7,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-elmer-5',
    date: '2026-07-05',
    sellerId: 'elmer',
    storeId: '102',
    salesWithTax: 11000,
    salesWithoutTax: 9322,
    productsSold: 13,
    clientsServed: 8,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },

  // --- Daniel (Tienda 218) ---
  {
    id: 'rec-daniel-1',
    date: '2026-07-01',
    sellerId: 'daniel',
    storeId: '218',
    salesWithTax: 14000,
    salesWithoutTax: 11864,
    productsSold: 16,
    clientsServed: 10,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-daniel-2',
    date: '2026-07-02',
    sellerId: 'daniel',
    storeId: '218',
    salesWithTax: 15000,
    salesWithoutTax: 12711,
    productsSold: 18,
    clientsServed: 11,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-daniel-3',
    date: '2026-07-03',
    sellerId: 'daniel',
    storeId: '218',
    salesWithTax: 11000,
    salesWithoutTax: 9322,
    productsSold: 13,
    clientsServed: 8,
    cleanlinessPassed: true,
    punctualityPassed: false,
  },
  {
    id: 'rec-daniel-4',
    date: '2026-07-04',
    sellerId: 'daniel',
    storeId: '218',
    salesWithTax: 16000,
    salesWithoutTax: 13559,
    productsSold: 20,
    clientsServed: 12,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-daniel-5',
    date: '2026-07-05',
    sellerId: 'daniel',
    storeId: '218',
    salesWithTax: 13000,
    salesWithoutTax: 11016,
    productsSold: 15,
    clientsServed: 9,
    cleanlinessPassed: false,
    punctualityPassed: true,
  },

  // --- Rossi (Tienda 218) ---
  {
    id: 'rec-rossi-1',
    date: '2026-07-01',
    sellerId: 'rossi',
    storeId: '218',
    salesWithTax: 9000,
    salesWithoutTax: 7627,
    productsSold: 10,
    clientsServed: 7,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-rossi-2',
    date: '2026-07-02',
    sellerId: 'rossi',
    storeId: '218',
    salesWithTax: 11000,
    salesWithoutTax: 9322,
    productsSold: 13,
    clientsServed: 9,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-rossi-3',
    date: '2026-07-03',
    sellerId: 'rossi',
    storeId: '218',
    salesWithTax: 8000,
    salesWithoutTax: 6779,
    productsSold: 9,
    clientsServed: 6,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-rossi-4',
    date: '2026-07-04',
    sellerId: 'rossi',
    storeId: '218',
    salesWithTax: 10000,
    salesWithoutTax: 8474,
    productsSold: 11,
    clientsServed: 8,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
  {
    id: 'rec-rossi-5',
    date: '2026-07-05',
    sellerId: 'rossi',
    storeId: '218',
    salesWithTax: 7000,
    salesWithoutTax: 5932,
    productsSold: 8,
    clientsServed: 5,
    cleanlinessPassed: true,
    punctualityPassed: true,
  },
];

export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'mission-1',
    title: 'Misión: Conquistador de Porcelanato Premium',
    description: 'Vender 10 unidades del Porcelanato Carrara Pulido entre el 10 y el 17 de Julio. ¡El ganador obtiene un bono de S/ 50!',
    startDate: '2026-07-10',
    endDate: '2026-07-17',
    rewardBono: 50,
    targetProduct: 'Porcelanato Carrara Pulido',
    targetQuantity: 10,
    active: true,
  },
  {
    id: 'mission-2',
    title: 'Misión: Escudo de Terrazas Rústicas',
    description: 'Vender 15 cajas de Cerámico Antideslizante rústico para terraza. ¡Bono de S/ 80 al primer guerrero en lograrlo!',
    startDate: '2026-07-01',
    endDate: '2026-07-08',
    rewardBono: 80,
    targetProduct: 'Cerámico Rústico Terraza',
    targetQuantity: 15,
    active: true,
  },
];

export const INITIAL_MISSION_PROGRESS: MissionProgress[] = [
  // Mission 1 (Carrara)
  { missionId: 'mission-1', sellerId: 'jose', progressCount: 6 },
  { missionId: 'mission-1', sellerId: 'elmer', progressCount: 4 },
  { missionId: 'mission-1', sellerId: 'daniel', progressCount: 7 },
  { missionId: 'mission-1', sellerId: 'rossi', progressCount: 3 },

  // Mission 2 (Rústico)
  { missionId: 'mission-2', sellerId: 'jose', progressCount: 12 },
  { missionId: 'mission-2', sellerId: 'elmer', progressCount: 15 }, // Completed!
  { missionId: 'mission-2', sellerId: 'daniel', progressCount: 10 },
  { missionId: 'mission-2', sellerId: 'rossi', progressCount: 9 },
];
